version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: challenge
      POSTGRES_PASSWORD: 6XQE9qddpNS4V
  graphql-engine:
    build:
      context: ./hasura
    env_file: ./hasura/.env
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always

volumes:
  db_data:

