version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: challenge
      POSTGRES_PASSWORD: 6XQE9qddpNS4V
  graphql-engine:
    build:
      context: ./hasura
    env_file: ./hasura/.env
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    
  next: 
    build: 
      context: ./frontend
    restart: always
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.next
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
  custom_graphql: 
    build: 
      context: ./custom_graphql_server
    restart: always
    volumes:
      - /app/node_modules
      - ./custom_graphql_server:/app
    ports:
      - 4000:4000
volumes:
  db_data:

