-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO long_tails (tail,json_id) VALUES
-- ('best-hello-ever', 1),
-- ('best-hello-world-ever', 2),
-- ('best-world-ever', 3);
